name: CD

on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install
        run: yarn install

      - name: Build & Export
        run: yarn export

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Add .nojekyll
        run: touch ./docs/.nojekyll
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
           add: 'docs'
           message: 'Publish post'
