name: CI

on:
  push:
    paths-ignore:
      - '_posts'
      - '_resume'
      - 'assets'

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install
      run: npm install
      
    - name: Test
      run: npm run test
      
    - name: Lint
      run: npm run lint
